name: github-pages

on:
  push:

permissions:
  contents: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Setup Python 3.10
        uses: actions/setup-python@v4.2.0
        with:
          python-version: '3.10'
      - name: merge usage documentation files into one
        run: python docs/md_merge.py --input docs/user --lang en --output docs --name author_guide.md
      - name: convert markdown to html
        uses: docker://pandoc/latex:2.19
        with:
          args: >-
            docs/author_guide.md
            -f markdown
            -t html
            -o public/index.html
            --lua-filter=docs/filters.lua
            --defaults=docs/defaults.yaml
      - name: deploy to GitHub pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
